version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - lll
    - mnd
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - wrapcheck
    - wsl
  settings:
    funlen:
      lines: -1
      statements: 40
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 100
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
        path: .*_test.go
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: 'ST1003: should not use underscores in package names'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
